#!/usr/bin/env python
from dbudget.controller import App
import site
import os
site.addsitedir(os.path.join(os.path.dirname(__file__), 'python'))


def main():
    App().cmdloop()

if __name__ == '__main__':
    main()

